Release/v3.4.0/include ncharts
dafiti-group/orb-standard-pipeline pull request #35
Opened 2024-02-15 18:21 UTC by lukas-lorenz

# PR Type

What kind of change does this PR introduce?

Irá adicionar deploy em ssc, no repositório do ncharts.

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?

Issue Number: [PLT-870](https://dafiti.jira.com/browse/PLT-870)

## The new version

New release version candidate: v3.4.0

>Reviewers, please check if the release candidate is present in the changes of this PR in the examples section!

## What is the new behavior?

Deploy in ssc

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2024-02-19 17:05 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:42765937485b5751e1d2ab1e130fab0d2a4c9bcd

2024-02-19 18:32 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:41b1893885de90e2101dd1fb13e9e0ccd993e93f

2024-02-19 21:02 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:ab7883adf3de24a5309ca18bf24edc2f0a757f4f

2024-02-20 21:47 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:b45742884d01047e746fda10d6056e91c0275ed4

2024-02-20 21:54 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:c43c3cbc17fa2b707ca4dd4d36362b5ef95342d3

2024-02-22 12:31 UTC, gritzkoo requested changes
tem algumas observações no script e está faltando um job `promote-gitlab` ou algo similar para fazer promoção de ambiente em ssc

2024-02-22 12:31 UTC, gritzkoo commented on src/examples/full-workflow-latam.yml
> +            context: [DEFAULT]
aqui não é passo de rollback @lorenz-lukas-dft

2024-02-22 12:31 UTC, gritzkoo commented on src/examples/full-workflow-latam.yml
> +    deployment-flow:
quando uma app tem mais de 1 ambiente live, tem que ter um bloco de revert para cada live...
por exemplo, uma app br co cl com live teria 3 passos aqui... e eles seriam:
```yaml
workflows:
    rollback-flow:
      when:
        or:
          - equal: [true, <<pipeline.parameters.rollback>>]
      jobs:
      - dft/eks-deploy:
            name: rollback-br-live
             # ....
      - dft/eks-deploy-latam:
            name: rollback-co-live
             # ....
      - dft/eks-deploy-latam:
            name: rollback-cl-live
             # ....
```

2024-02-23 15:00 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:90ee253ebe5c9397be45a81cf0ef4461f80fee6b

2024-02-23 19:30 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:f24ad5306d8b28cad785cd7258c04913402377a4

2024-02-23 20:46 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:6b71c665c5a7adcccd765266dc45b6f9b1824bdf

2024-02-27 18:54 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:ae430f407c2cdfa9eac7a8ab64fb15c17444d99c

2024-02-28 20:52 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:a46988e26744a92d1cbc9f89c875ea5e4c13379e

2024-02-29 16:20 UTC, gritzkoo submitted a review, later dismissed

2024-02-29 19:30 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:aff80417840c9947faba5573c7fd27254b614ba5

2024-02-29 20:20 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:b0aee16849159d59025daab64f76030cf0125b2e

2024-03-01 20:06 UTC, caykemanjanelli commented on CHANGELOG.md
> +
include country in `instana` message notification

2024-03-04 13:07 UTC, caykemanjanelli approved these changes

2024-03-04 13:09 UTC, merged

2024-03-04 13:09 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:3830258ad5108c7fe75d9133db922788d06a6025

2024-03-04 13:13 UTC, dft-deploy commented
Your orb has been published to the CircleCI Orb Registry.
You can view your published orb on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=3.4.0

2024-04-26 19:50 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:3830258ad5108c7fe75d9133db922788d06a6025