deploy statis files to S3
dafiti-group/orb-standard-pipeline pull request #36
Opened 2024-04-26 13:27 UTC by dft-afinoti

# PR Type

What kind of change does this PR introduce?

Adding possibility to send static files to S3.

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting)
- [ ] Refactoring (no functional changes)
- [ ] CI related changes
- [ ] Other... Please describe:

## What is the current behavior?
It is necessary to use docker to build image and send

2024-04-26 13:50 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:154b5f851144091f1d1d3af94c8fc7eac11fc434

2024-04-26 13:53 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:0ab7eb2551239c4f016cbb1e039dff099d9384af

2024-05-06 19:16 UTC, dft-deploy commented
Your development orb has been published. It will expire in 30 days.
You can preview what this will look like on the CircleCI Orb Registry at the following link: 
https://circleci.com/developer/orbs/orb/dafiti-group/orb-standard-pipeline?version=dev:1126219093120ae68b675622dc2c7eaef668887b

2024-05-09 18:50 UTC, bernard0le approved these changes

2024-05-09 19:25 UTC, caykemanjanelli requested changes

2024-05-09 19:25 UTC, caykemanjanelli commented on src/jobs/static-deploy-to-s3.yaml
> +      custom: <<include(templates/fail.json)>>
Precisa completar essa versão com suas documentações e chamgelog

2024-06-10 21:58 UTC, caykemanjanelli commented
Closed PR, merged in #37 to delivety

2024-06-10 21:58 UTC, closed without merging